import type { MenuProductData } from '@elements/MenuProduct.astro'

export const productsData: Array<MenuProductData> = [
  {
    pid: '1',
    amount: 0,
    price: 1000,
    oldPrice: false,
    categories: ['Простые карточки'],
    subcategories: false,
    labels: false,
    name: 'Карточка',
    description: false,
    feature: false,
    stats: [
      {
        title: 'Вес',
        value: '111 г.',
      },
    ],
    variants: false,
    type: 'large',
    energy: { proteins: '111', fats: '111', carbohydrates: '111', calories: '111' },
    image: '/images/food/1.jpg',
    href: '/products/simple',
  },
  {
    pid: '2',
    amount: 0,
    price: 1000,
    oldPrice: false,
    categories: ['Простые карточки'],
    subcategories: ['С описанием'],
    labels: false,
    name: 'Карточка с описанием',
    description: 'Описание карточки',
    feature: false,
    stats: [
      {
        title: 'Вес',
        value: '111 г.',
      },
    ],
    variants: false,
    type: 'large',
    energy: { proteins: '111', fats: '111', carbohydrates: '111', calories: '111' },
    image: '/images/food/2.jpg',
    href: '/products/simple',
  },
  {
    pid: '3',
    amount: 0,
    price: 1000,
    oldPrice: false,
    categories: ['Простые карточки'],
    subcategories: ['С иконкой eco'],
    labels: false,
    name: 'Карточка с иконкой',
    description: false,
    feature: 'eco',
    stats: [
      {
        title: 'Вес',
        value: '111 г.',
      },
    ],
    variants: false,
    type: 'large',
    energy: { proteins: '111', fats: '111', carbohydrates: '111', calories: '111' },
    image: '/images/food/3.jpg',
    href: '/products/simple',
  },
  {
    pid: '4',
    amount: 0,
    price: 1000,
    oldPrice: false,
    categories: ['Простые карточки'],
    subcategories: ['С иконкой spicy'],
    labels: false,
    name: 'Карточка с иконкой',
    description: false,
    feature: 'spicy',
    stats: [
      {
        title: 'Вес',
        value: '111 г.',
      },
    ],
    variants: false,
    type: 'large',
    energy: { proteins: '111', fats: '111', carbohydrates: '111', calories: '111' },
    image: '/images/food/1.jpg',
    href: '/products/simple',
  },
  {
    pid: '5',
    amount: 0,
    price: 1000,
    oldPrice: 2000,
    categories: ['Простые карточки'],
    subcategories: ['Со скидкой'],
    labels: false,
    name: 'Карточка со скидкой',
    description: false,
    feature: false,
    stats: [
      {
        title: 'Вес',
        value: '111 г.',
      },
    ],
    variants: false,
    type: 'large',
    energy: { proteins: '111', fats: '111', carbohydrates: '111', calories: '111' },
    image: '/images/food/1.jpg',
    href: '/products/simple',
  },
  {
    pid: '6',
    amount: 0,
    price: 1000,
    oldPrice: false,
    categories: ['Простые карточки'],
    subcategories: ['С лейблами'],
    labels: [
      { color: '#1A8704', value: 'Новинка' },
      { color: '#E53935', value: 'Акция 10%' },
    ],
    name: 'Карточка с лейблами',
    description: false,
    feature: false,
    stats: [
      {
        title: 'Вес',
        value: '111 г.',
      },
    ],
    variants: false,
    type: 'large',
    energy: { proteins: '111', fats: '111', carbohydrates: '111', calories: '111' },
    image: '/images/food/1.jpg',
    href: '/products/simple',
  },
  {
    pid: '7',
    amount: 0,
    price: 1000,
    oldPrice: false,
    categories: ['Простые карточки'],
    subcategories: ['Несколько изображений'],
    labels: false,
    name: 'Карточка с несколькими изображениями',
    description: false,
    feature: false,
    stats: [
      {
        title: 'Вес',
        value: '111 г.',
      },
    ],
    variants: false,
    type: 'large',
    energy: { proteins: '111', fats: '111', carbohydrates: '111', calories: '111' },
    image: '/images/food/1.jpg',
    href: '/products/simple',
  },
  {
    pid: '8',
    amount: 0,
    price: 1000,
    oldPrice: 2000,
    categories: ['Простые карточки'],
    subcategories: [
      'С описанием',
      'С иконкой spicy',
      'Со скидкой',
      'С лейблами',
      'Несколько изображений',
    ],
    labels: [
      { color: '#1A8704', value: 'Новинка' },
      { color: '#E53935', value: 'Акция 10%' },
    ],
    name: 'Карточка со всем вместе',
    description: false,
    feature: 'spicy',
    stats: [
      {
        title: 'Вес',
        value: '111 г.',
      },
    ],
    variants: false,
    type: 'large',
    energy: { proteins: '111', fats: '111', carbohydrates: '111', calories: '111' },
    image: '/images/food/1.jpg',
    href: '/products/simple',
  },
  {
    pid: '9',
    amount: 0,
    price: 1000,
    oldPrice: false,
    categories: ['Карточки с вариантами'],
    subcategories: false,
    labels: false,
    name: 'Карточка с вариантами',
    description: 'Описание карточки',
    feature: false,
    stats: [
      {
        title: 'Вес',
        value: '111 г.',
        variantProp: 'size',
      },
    ],
    variants: [
      {
        name: '4 шт.',
      },
      {
        name: '8 шт.',
      },
    ],
    type: 'large',
    energy: { proteins: '111', fats: '111', carbohydrates: '111', calories: '111' },
    image: '/images/food/1.jpg',
    href: '/products/variants',
  },
  {
    pid: '10',
    amount: 0,
    price: 1000,
    oldPrice: false,
    categories: ['Карточки с сетами'],
    subcategories: false,
    labels: false,
    name: 'Карточка с сетом',
    description: 'Описание карточки',
    feature: false,
    stats: [
      {
        title: 'Вес',
        value: '111 г.',
        variantProp: 'size',
      },
      {
        title: '',
        value: '32 шт.',
        border: true,
      },
    ],
    variants: false,
    type: 'large',
    energy: { proteins: '111', fats: '111', carbohydrates: '111', calories: '111' },
    image: '/images/food/1.jpg',
    href: '/products/set',
  },
]
